### ISSUE TITLE
Issues with Svgdotjs

### ISSUE THREAD

**Issue by thorlucas** [omnibrain/svguitar#82] opened 2022-01-17 04:41 UTC
I am using the very simple sample code in React:

```typescript
	const chart = new SVGuitarChord('#am')
		.chord({
			fingers: [
				[1, 2, 'E'],
				[2, 3, 'A'],
				[3, 1, 'C'],
				[4, 0, 'E'],
			],
			barres: [],
		})
		.configure({
			strings: 4,
			frets: 4,
			tuning: ['D', 'C', 'G', 'E'],
		})
		.draw();
	return (
		<span id="am"></span>
	);
```

We get the following trace:

```
TypeError: Cannot read properties of null (reading 'put')
Svg.addTo
node_modules/@svgdotjs/svg.js/src/elements/Dom.js:44
  41 | 
  42 |  // Add element to given container and return self
  43 |  addTo (parent) {
> 44 |    return makeInstance(parent).put(this)
     | ^  45 |  }
  46 | 
  47 |  // Returns all child elements
View compiled
new SvgJsRenderer
src/renderer/svgjs/svg-js-renderer.ts:27
  24 |   this.svg = SVG(container) as Container
  25 | } else {
  26 |   // browser
> 27 |   this.svg = SVG().addTo(container)
     | ^  28 | }
  29 | 
  30 | this.svg.attr('preserveAspectRatio', 'xMidYMid meet').viewbox(0, 0, width, height)
View compiled
SVGuitarChord.get
src/svguitar.ts:387
  384 | 
  385 | switch (style) {
  386 |   case ChordStyle.normal:
> 387 |     this.rendererInternal = new SvgJsRenderer(this.container)
      | ^  388 |     break
  389 |   case ChordStyle.handdrawn:
  390 |     this.rendererInternal = new RoughJsRenderer(this.container)
View compiled
SVGuitarChord.clear
src/svguitar.ts:1134
  1131 | }
  1132 | 
  1133 | clear(): void {
> 1134 |   this.renderer.clear()
       | ^  1135 | }
  1136 | 
  1137 | /**
View compiled
SVGuitarChord.draw
src/svguitar.ts:422
  419 | }
  420 | 
  421 | draw(): { width: number; height: number } {
> 422 |   this.clear()
      | ^  423 |   this.drawBackground()
  424 | 
  425 |   let y
View compiled
App
src/components/App/index.tsx:15
  12 | 	],
  13 | 	barres: [],
  14 | })
> 15 | .configure({
     | ^  16 | 	strings: 4,
  17 | 	frets: 4,
  18 | 	tuning: ['D', 'C', 'G', 'E'],
View compiled
▶ 17 stack frames were collapsed.
Module.<anonymous>
src/index.tsx:6
  3 | import './index.css';
  4 | import App from '@components/App';
  5 | 
> 6 | ReactDOM.render(
  7 | 	<React.StrictMode>
  8 | 		<App />
  9 | 	</React.StrictMode>,
View compiled
Module../src/index.tsx
```

**Comment by omnibrain** [comment] 2022-01-17 08:02
Hi @thorlucas, I'm sorry to hear you're experiencing problems with the library. 

I think the problem is that when `.draw()` is called, the DOM element with the id "am" does not yet exist. Can you try to wrap the SVGuitar code in a `useEffect`? Like so:

```javascript
useEffect(() => {
const chart = new SVGuitarChord('#am')
		.chord({
			fingers: [
				[1, 2, 'E'],
				[2, 3, 'A'],
				[3, 1, 'C'],
				[4, 0, 'E'],
			],
			barres: [],
		})
		.configure({
			strings: 4,
			frets: 4,
			tuning: ['D', 'C', 'G', 'E'],
		})
		.draw();
}, [])

return (
  <span id="am"></span>
);
```

**Comment by omnibrain** [comment] 2022-01-17 12:15
I'm going to close this issue for now. If my proposed solution does not work I will reopen the issue again.

**Closed by omnibrain** 2022-01-17 12:15 UTC

**Comment by jhigginson** [comment] 2022-07-03 02:48
The provided solution ended up drawing the svg twice within the span, so I added a check inside the useEffect() before the creation of the svg to remove if there is a child already like so:

```JavaScript
    const container = document.getElementById('am');
    if (container.childElementCount > 0) {
      container.firstChild.remove();
    }
```

**Comment by jktravis** [comment] 2022-07-17 18:31
> The provided solution ended up drawing the svg twice within the span, so I added a check inside the useEffect() before the creation of the svg to remove if there is a child already like so:
> 
> ```js
>     const container = document.getElementById('am');
>     if (container.childElementCount > 0) {
>       container.firstChild.remove();
>     }
> ```

You might just need to add a clean up function to your effect. 

```js
useEffect(() => {
    const chart = new SVGuitarChord({/*...*/});
    
    chart.draw();

    return () => chart.remove();
}, [/*..*/])
